const ADD_ARTIST = 'ADD_ARTIST';
const EDIT_ARTIST = 'EDIT_ARTIST';
const ADD_ARTIST_PICTURE = 'ADD_ARTIST_PICTURE';
const INCREMENT_STARS = 'INCREMENT_STARS';
const DECREMENT_STARS = 'DECREMENT_STARS';
